name: ios-deployment

on:
  push:
    branches:
      - 'release/*'

jobs:
  deploy:
    runs-on: macos-latest
    env:
      APPLE_ID: ${{ secrets.APPLE_ID }}
      ASC_KEY_ID: ${{ secrets.ASC_KEY_ID }}
      ASC_ISSUER_ID: ${{ secrets.ASC_ISSUER_ID }}
      ASC_KEY_CONTENT: "${{ secrets.ASC_PRIVATE_KEY }}"
      MATCH_GIT_PRIVATE_KEY: ${{ secrets.MATCH_GIT_PRIVATE_KEY }}
      MATCH_PASSWORD: ${{ secrets.MATCH_PASSWORD }}

    steps:
      - uses: actions/checkout@v4
      - uses: maxim-lobanov/setup-xcode@v1
        with:
          xcode-version: latest-stable
      - uses: ruby/setup-ruby@v1
        with:
          ruby-version: 3.2.1
          bundler-cache: true
      - run: bundle exec fastlane ios beta
      - uses: actions/upload-artifact@v4
        with:
          name: appstore ipa & dsym
          path: |
            ${{ github.workspace }}/fastlane/builds/flo.ipa
            ${{ github.workspace }}/fastlane/builds/flo.app.dSYM.zip
